version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Qazqazwsx1
      MYSQL_DATABASE: communication
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
