# Generated by Django 4.2 on 2023-04-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_date_created_alter_users_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_created',
        ),
    ]
