# Generated by Django 4.2 on 2023-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_is_staff_alter_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
