# Generated by Django 4.2 on 2023-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_users_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Customers",
            },
        ),
    ]
